name: Curso platzi hola mundo

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo "Test"
      - name: Test 1
        run: echo "Test 1 ${{ github.event_name }}"
